### ISSUE TITLE
Scroll bug in reviewer notes (record level)

### ISSUE THREAD

**Issue by jmotis** [chnm/Datascribe-module#11]
As I typed reviewer notes into the side panel in the edit record view, it scrolled the record view. Any text input (including deleting previous texts) continued the scroll. This behavior isn't replicated in the transcriber notes field, just the reviewer notes.

![reviewer-scroll-bug](https://user-images.githubusercontent.com/8195932/78807667-62eb5f00-7992-11ea-98fc-555009d67dcc.png)

**Comment by jimsafley** [comment]
I cannot reproduce this. @kimisgold Can you confirm?

**Comment by jmotis** [comment]
I can't reproduce it now, either. Close until/unless it reoccurs?
