### ISSUE TITLE
Need way to get sidebar back after minimizing

### ISSUE THREAD

**Issue by jmotis** [chnm/Datascribe-module#12]
When I minimize the sidebar on the right, there currently doesn't seem to be a way to get the sidebar back other than reloading the page.

![sidebar](https://user-images.githubusercontent.com/8195932/78807970-c83f5000-7992-11ea-9b71-b3afa19d6c50.png)

**Comment by jimsafley** [comment]
I cannot reproduce this. There should be a sidebar expand button along the right side of the page. @kimisgold can you confirm?

**Comment by jmotis** [comment]
I experimented with this a bit more and it appears to be a browser-specific (Safari) problem as I see the sidebar expand button when I switch to Firefox.  On Safari, clicking on the edge of the right side of the page does expand the sidebar but there's nothing visually signaling that the sidebar is still there (Safari Version 12.1.2 (14607.3.9) on macOS Mojave)
