### ISSUE TITLE
Disambiguate item and record note fields

### ISSUE THREAD

**Issue by mebrett** [chnm/Datascribe-module#128]
Users are having trouble tracking whether they are leaving notes in the **item** notes or the **record** note. Simplest way to resolve might be to change the field names from "Review notes" to "Review item notes" and "Reviewer record notes" etc

**Comment by hepplerj** [comment]
Just to clarify, you mean these labels in the DataScribe entry pane?

<img width="336" alt="Reviewer item records text input" src="https://user-images.githubusercontent.com/153271/206303027-ff83faf4-af80-477e-b23f-0ffe286c1e77.png">

**Comment by mebrett** [comment]
Yes - the appearance of the note is the same whether you're in the "Item Actions" or "Record Actions" panels. Because they look similar, folks were getting confused about whether they stored the same information. We were also getting miscommunication of "I left it in the notes" with "I can't find it" bc looking at different notes fields. 

Just tweaking to "Transcriber/Reviewer item notes" and "Transcriber/Reviewer record notes" should work

**Comment by hepplerj** [comment]
Great, thank you. By my reckoning, it looks like there are just four template files to update. I'll give that an attempt on a local test version and see how it goes.
