### ISSUE TITLE
[JOSS] Consider adjusting documentation screenshots with more concrete values

### ISSUE THREAD

**Issue by luxaritas** [chnm/Datascribe-module#134]
Part of https://github.com/openjournals/joss-reviews/issues/5661

Bit of a nitpick on the really nice docs, open to opinions on how useful or not this would be. You might want to consider tweaking the screenshots in the documentation to be a bit more concrete. It seems like a lot of screenshots have completely empty form fields, where having example data filled in could help clarify the usage and help strengthen the ask for "solving real-world analysis problems".

**Comment by jmotis** [comment]
Thanks for the suggestion. We actually have built up a whole series of case studies and tutorial videos that use real-world data from our various projects but it's on the [project website](https://datascribe.tech) not the GitHub. The website links here but the GitHub doesn't link back, which is an easy fix.
