### ISSUE TITLE
[JOSS] Install link not working

### ISSUE THREAD

**Issue by koenedaele** [chnm/Datascribe-module#135]
Part of openjournals/joss-reviews#5661

At https://datascribe.tech/support/quickstart/, the install points to https://omeka.org/s/modules/Datascribe-module/ but this page does not exist.

**Comment by koenedaele** [comment]
The correct link seems to be https://omeka.org/s/modules/Datascribe/

**Comment by hepplerj** [comment]
Resolved in chnm/datascribe-site@745ef1d684499994757658251558fb66972cf005.
