### ISSUE TITLE
Fill whitespace on module start-up page

### ISSUE THREAD

**Issue by jmotis** [chnm/Datascribe-module#14]
We don't have a plan for this page that I've forgotten about, do we?  Because we have a lot of whitespace here we should probably fill, I'm thinking with a bit of grounding text, e.g. "Welcome to the DataScribe module. To get started, create a new project using the menu in the upper right-hand corner. For full module documentation, see <insert link here>."

![blank-screen](https://user-images.githubusercontent.com/8195932/78808369-50bdf080-7993-11ea-9192-4cc449a98cd8.png)

**Comment by jimsafley** [comment]
We have no plan for this page, at least nothing concrete. Dashboards typically are geared toward the needs of the current user - like links to recent work, status updates, and alerts. We should use this issue to discuss the dashboard, but lets hold off on implementation until user testing makes our needs more obvious. For now I'll just add the grounding text.

**Comment by jimsafley** [comment]
As for the most relevant needs of the current user, here are some ideas of short lists we can provide:

- **My projects**: links to projects to which the user belongs (reviewer and transcriber)
- **My new items**: ; order by date locked, earliest first
- **My in progress items**: order by date locked, earliest first
- **My items that are not approved**: order by date reviewed, earliest first
- **All unlocked and new items**: order by date created, earliest first
- **All unlocked and in progress items**: order by date created, earliest first
- **All items that need review**: order by date submitted, earliest first; reviewer only
- **Items I reviewed that need re-review**: order by date submitted, earliest first; reviewer only

Note that most of these already exist as item filters, but would be across _all_ datasets, and would only appear when applicable to the current user. Opinions?
