### ISSUE TITLE
Workflow issue - need to be able save form builder progress and continue

### ISSUE THREAD

**Issue by jmotis** [chnm/Datascribe-module#17]
When I was trying to build my test form (which is long... there are over a hundred parishes in each bill of mortality) I kept wanting to save my progress, which booted me back to the main screen where I had to click several times to get back to the form builder. This is especially important since I need to save before the name field displays, which will be important to keep my place while I'm adding fields once I switch over to using actual parish names.

![builder-nameless](https://user-images.githubusercontent.com/8195932/78809409-e017d380-7994-11ea-9866-3f7e59904a39.png)

![name-updated](https://user-images.githubusercontent.com/8195932/78809557-1fdebb00-7995-11ea-9210-5b8be45131a2.png)

**Comment by jimsafley** [comment]
Would it be sufficient to provide a save button that returns you directly back to the form builder? The nature of the form makes it extremely difficult to save state asynchronously.

**Comment by jmotis** [comment]
Yes, that would be perfect.

**Comment by jimsafley** [comment]
@kimisgold I added a "Save progress" button that returns the user to the form builder. One concern I have is that the button is currently visible on both the "Form builder" and "General" sections. Given that it returns the user directly to the form builder, should we move the "Save progress" button to somewhere in the "Form builder" section, like at the bottom of the form, or at the top of the sidebar? Is this even a problem worth considering?

**Comment by kimisgold** [comment]
I like the top of the sidebar. It doesn't take up much space and stays visible through the whole form editing workflow.

I'm also wondering if we could also do the form submission via ajax or something where the user would not actually be taken away from the view. Currently you're returned to the view with all fields collapsed, which seems disruptive to the workflow. I'd imagine the the "saved" notification would appear under the button, possibly with a timestamp.

![Screen Shot 2020-04-21 at 2 48 42 PM](https://user-images.githubusercontent.com/606764/79903285-cccb2600-83e0-11ea-8a5e-25aade3ebc92.png)

**Comment by jimsafley** [comment]
As you see in #2, submitting the form as a background request is... problematic. I strongly prefer we come up with a second best solution. I could make it so the fields don't collapse after saving progress, and I could _possibly_ manage keeping the page scrolled near where it was when the progress was saved. I like the idea of having a "last saved" prompt. Thoughts?

**Comment by kimisgold** [comment]
Open fields and resuming approximate page scroll position after saving progress sounds fine to me.

**Comment by jimsafley** [comment]
in lieu of a perfect solution, and since we've added a "Save progress" button, I'm going to close this issue. Keep an eye on #2 for any further movement.
