### ISSUE TITLE
Reexamine view options for vertical images

### ISSUE THREAD

**Issue by jmotis** [chnm/Datascribe-module#19]
Right now, we seem to be optimized for horizontal images and vertical images aren't displaying very well. Even when I minimize the sidebars to maximize the view, the image is way too small to transcribe without zooming in, which then requires a lot of mousework to fiddle and readjust with placement as I transcribe.

![vertical-image0](https://user-images.githubusercontent.com/8195932/78810383-46512600-7996-11ea-994b-672712083358.png)

![vertical-image1](https://user-images.githubusercontent.com/8195932/78810388-47825300-7996-11ea-90ff-ccd54541d325.png)

![vertical-image2](https://user-images.githubusercontent.com/8195932/78810403-4bae7080-7996-11ea-9b92-b03d83935889.png)

**Comment by kimisgold** [comment]
I'm working on re-implementing the fullscreen view as well as some vertical and horizontal layout options, mimicking features from Scripto. In the full screen view, I'm currently focusing on including the only the media viewer and the main record form for a more focused view.

**Comment by kimisgold** [comment]
I've got a rough draft of the full screen toggle on the `record-layout` branch. The "focus mode" button toggles a view where the current row form takes up most of the screen. The horizontal and vertical layout buttons toggle between two column and stacked layouts. Could you check that out @jmotis and see how you like it?

**Comment by jmotis** [comment]
That's definitely better and focus mode is looking great, especially the stacked layout. There's still a lot of whitespace in the bottom right hand corner of the two column layout, though, which would be nice if we could use for the image as well? I'm imagining something like my (very bad) Photoshop here, where I cut-pasted one of my research images onto a screenshot - you can see the original proportions of the document would let it fill that whole side area compared to the smaller/more square image.

![more-vertical](https://user-images.githubusercontent.com/8195932/79388976-327c6580-7f3c-11ea-9440-350388d1d848.jpg)
![square](https://user-images.githubusercontent.com/8195932/79388986-33ad9280-7f3c-11ea-8238-ecc46d72ed65.png)

**Comment by kimisgold** [comment]
(For clarification, do you mean the bottom left corner of the layout?)

With regard to the sizing of the media viewer, it's currently set to use the aspect ratio of the media; I assumed the square container you're seeing is from the original square media your research photos is replacing. A portrait image within the horizontal layout will be sized to take up the maximum width of the media viewer column and have its height scaled accordingly. I think we could have the media viewer height set to take up the full vertical space of the form. If so, there'd still be a bunch of white space underneath the image on load, but at least when zooming, more of the image would be viewable. I'll experiment with it this afternoon.

**Comment by jmotis** [comment]
Yes, the bottom left corner of the layout, sorry.

**Comment by kimisgold** [comment]
I've just pushed a full row height media viewer. Image media are currently vertically centered, but that's an easy change if top aligned makes more sense.

**Comment by jmotis** [comment]
Much better, thanks! We might want to play with it more in the beta version, but I think that's good for now.
