### ISSUE TITLE
Need to be able to select flag with keyboard

### ISSUE THREAD

**Issue by jmotis** [chnm/Datascribe-module#20]
When I tab through the fields, it tabs through each of the flags but there doesn't seem to be any way to select one of the flags with the keyboard - the only active key I've been able to find is the enter key which just saves the record and takes me back to the record page.

![flag-keyboard-action](https://user-images.githubusercontent.com/8195932/78810762-c8414f00-7996-11ea-97cf-2056b6c53120.png)

**Comment by jimsafley** [comment]
I believe @kimisgold is currently working on restyling the record form. Once that it done I can look into this.

**Comment by kimisgold** [comment]
This is a quirk of Safari, which does not let you focus inputs, like those flags' checkboxes, by default: you have to go into Preferences > Advanced > Accessibility and select "Press Tab to highlight each item on a webpage". The spacebar will let you toggle the checkbox state once that setting is active.
