### ISSUE TITLE
Find place for transcription guidelines

### ISSUE THREAD

**Issue by jimsafley** [chnm/Datascribe-module#22]
We need to find a place to display the guidelines for transcribing a dataset. Logically, they belong somewhere on the record add/edit form, but I'm not sure how we display them. What makes the most sense for a transcriber? A separate tab? A modal window? Always available at the bottom of the page?

**Comment by mebrett** [comment]
How long do we think people's guidelines are going to be? @jmotis and @lmullen - is this going to be short instructions which might fit on the record page? Or something longer and more involved?

**Comment by jmotis** [comment]
I think it will vary, I definitely could see something like the 1-page Scripto guidelines as being a reasonable set of transcription guidelines for some projects.

**Comment by jimsafley** [comment]
One thing to consider is that, unlike Scripto, DataScribe includes customizable descriptions for each field in a record form. Assuming form builders add field-specific guidelines to these descriptions, there may be less need (but not no need) for general guidelines.

**Comment by lmullen** [comment]
For reference, the Religious Ecologies guidelines for [transcribing census schedules](https://3.basecamp.com/4265114/buckets/13357949/documents/2006959047) are about 550 words long, and the guidelines for [transcribing published records](https://3.basecamp.com/4265114/buckets/13357949/documents/2108989975) are about 380 words long. But as @jimsafley points out, at least some of that is for field-specific guidelines.

**Comment by kimisgold** [comment]
For general guidelines, we could place them in a collapsible area in the sidebar above the reviewer actions. I've done a local test with Lincoln's examples, and while it's a lot of content in that area, it may not be so bad if you can toggle that information.

**Comment by kimisgold** [comment]
"Show guidelines button" opposite "focus mode" that opens a lightbox.

**Comment by dth1692** [comment]
For the Queen Elizabeth's Household Officers, I can't see @jmotis'  transcription guidelines anywhere.  This is on my Global Administrator account, so can only the project owner see them for now?

**Comment by jimsafley** [comment]
This feature hasn't been implemented yes, as far as I know.

**Comment by jmotis** [comment]
Right now, the only place I know to see them is when you "edit dataset" it pops up with the dataset metadata so you ought to be able to see them as a global admin but you do have to look for them.

**Comment by dth1692** [comment]
Yep- just found it there
