### ISSUE TITLE
Custom data types

### ISSUE THREAD

**Issue by jimsafley** [chnm/Datascribe-module#24]
Currently, modules can add custom DataScribe data types using the `datascribe_data_types` configuration. What we need now is a real-world example of a data type that tests the limits of DataScribe's capabilities. Specifically, can data types accommodate dynamic content? Can they use external sources of data to populate, validate, and render content?

**Comment by jimsafley** [comment]
I think a good start is a data type that's been proposed for the [American Religious Ecologies module](https://github.com/chnm/Mare-module) - that is, a "Populated place" field that provides an interface to select a uniquely identified place from an hierarchical list of `states -> counties -> places`, drawing the data from an API.

@lmullen Where exactly is the populated places dataset? Is it currently available via an API?

**Comment by lmullen** [comment]
Here's the dataset: https://3.basecamp.com/4265114/buckets/13357949/uploads/2006956957

**Comment by lmullen** [comment]
Working on this over here: https://github.com/chnm/dataapi/issues/7

**Comment by jimsafley** [comment]
I've created a working custom data type for the [Mare module](https://github.com/chnm/Mare-module/compare/datascribe-data-type-populated-place) that uses the Center's ["Populated places" API](https://data.chnm.org/). This addresses the purpose of this issue, so I'll close it.
