### ISSUE TITLE
Dashboard feedback

### ISSUE THREAD

**Issue by kimisgold** [chnm/Datascribe-module#27]
I've applied some changes to the dashboard on the `dashboard` branch:

* **Pulled browse/add projects actions out as buttons**: I found we were repeating these actions in the top bar and in the main content area. There are only two of them, and both have short strings. 

* **Included recently modified projects**: I created a simplified listing of the 10 most recently modified projects. It links to the project and shows when it was last modified.

* **Re-organized filters within My Projects**: I tried to organize the filters to be more scannable at a glance while also reducing unique strings.

I would appreciate folks trying out these new styles, especially those who have many projects within their installation.

![image](https://user-images.githubusercontent.com/606764/82214832-6f919a00-98e4-11ea-9db8-47a965bcd46a.png)

**Comment by mebrett** [comment]
The testing instance is now on this branch.

**Comment by jimsafley** [comment]
I notice you switched to using the Laminas namespace. We're going to keep using the Zend namespace until after we release Omeka S 3.0. You're going to need to switch it back.

To be clear, DataScribe only updates a project's modified date-time when a user saves the project form, not any time something happens within the project - e.g. when an item is submitted for review or a new record is created. I see the usefulness of a list of projects on the dashboard, but specifying them as "recently modified" may lead to misunderstandings. Here I think we can safely have a list of all projects ordered alphabetically by name.

**Comment by kimisgold** [comment]
The branch should be updated to use the Zend namespace, as well as list all projects alphabetically and with a creator column.

**Comment by jimsafley** [comment]
Take with a grain of salt, but I prefer:
- Unlocked items: New, In progress
- My items: New, In progress
- Items needing review: All, Needs my re-review

I like the idea of pulling actions out as buttons. We should do it for the dataset show page: Edit project, Add new dataset. That leaves the dataset show page the only one with an actions dropdown. Is there a way to pull those out too? Not sure about that.

**Comment by kimisgold** [comment]
I like the consistency in your filter order. Looks good to me.

I also think it's okay to have only the dataset show page be the only page with the actions dropdown, as it has many that are hard to condense. One idea for it, though: we could pull out the most commonly used action, and leave the others in a "More actions" or "..." dropdown.

**Comment by jimsafley** [comment]
I really like the idea of pulling out "Edit dataset" and leaving the rest under a "More actions" dropdown.

**Comment by mebrett** [comment]
Am I right in understanding that only projects which are 'public' show up in the All Projects display?

**Comment by mebrett** [comment]
In case anyone was wondering what it looks like for a transcriber (not global admin): 
<img width="1157" alt="Screen Shot 2020-05-19 at 11 16 23 AM" src="https://user-images.githubusercontent.com/2314070/82344626-49dac280-99c2-11ea-8c76-c93424397e4d.png">

**Comment by jimsafley** [comment]
All users should be able to see all _public_ projects. Only global admins and site admins should be able to see _private_ projects to which they don't belong. So, for example, a researcher, author, or editor who is not assigned to a private project should not be able to see that project. This all applies to datasets as well.

**Comment by mebrett** [comment]
I'm not seeing private projects (to which I do not belong) in the all projects dashboard view; I do see them when I go to the Browse Projects. (logged in as me, not as transcriber user)

**Comment by jimsafley** [comment]
@mebrett I forgot to ask whether the newest change fixed the above problem. Did it?

**Comment by mebrett** [comment]
I'm still only seeing public projects in the All Projects on the dashboard. I do see al projects when I go to browse

**Comment by lmullen** [comment]
A question about the distinction between "new" and "in progress" items for the dashboard. I believe @jimsafley said that the distinction is that new items have no records, while in progress do. 

That distinction seems to hold for the "My items" row. An item with at least one record shows up in "in-progress." It doesn't seem to hold for "unlocked items." There are two items in the "Paulist Mission Chronicles" dataset that have media but no records, but they show up in unlocked "in-progress" rather than "new."

**Comment by lmullen** [comment]
A question about the distinction between "new" and "in progress" items on the dashboard. For "my items," it appears that items with records show up as "in progress," which makes sense. For unlocked items, there are two items in the "Paulist Mission Chronicles" dataset which have media but no items. I would expect those to show up under "new," but they show up under "in progress." Is that expected?

**Comment by jimsafley** [comment]
Ah, the "new" and "in progress" filter strings were switched. It should be fixed now. Thanks for finding the bug.
