### ISSUE TITLE
Scrolling on edit record form

### ISSUE THREAD

**Issue by lmullen** [chnm/Datascribe-module#28]
I created a record, saved my progress, and then came back to it. I can't then scroll the form, though I can scroll the right hand sidebar. If I resize the browser window to make it taller, I can see more of the form below.

Here's the [item in question](http://datascribetest.chnm.org/admin/datascribe/4/5/101/13/edit) on the testing site. Screenshot:

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/183672/82463787-42332080-9a8b-11ea-98d6-7316621bf7c4.png">

**Comment by kimisgold** [comment]
I can scroll both at the moment using my scroll wheel while hovering with the cursor over each section. Just tested on Chrome and Firefox. What browser are you using?

**Comment by lmullen** [comment]
I was on Safari. Just went to test it in Firefox myself but the data just got nuked. :-)

**Comment by kimisgold** [comment]
The above commit should now be on the main test instance.
