### ISSUE TITLE
Clean up item-show branch

### ISSUE THREAD

**Issue by jimsafley** [chnm/Datascribe-module#3]
To the extent possible, I need you to clean up the `item-show` branch. I will begin implementing the record wireframes therein and need to start from a prepared state. This includes removing cruft (unused CSS and JS), cleaning up existing markup, and ensuring that we're using design patterns consistent with Omeka's administrative interface. This does not mean I want a definitive version of the interface. I just want some assurance that the wireframes are prepared for me to copy over to the `master` branch.

**Comment by kimisgold** [comment]
I did at least a first pass at cleaning up the JS in https://github.com/chnm/Datascribe-module/commit/7c693e59d56a9383cf3928e5c137e047e2b4d4f6. At that point, I didn't see any CSS rules I'd written that aren't currently in use.
