### ISSUE TITLE
Feedback for common element checkboxes in record form

### ISSUE THREAD

**Issue by kimisgold** [chnm/Datascribe-module#30]
In the `record-form` branch, I've styled the record form's common element checkboxes ("is missing", "is illegible", "set to null") to be more vertically compact and better represent the "set to null" option, currently labeled as "reset value". Other notes: 

* "Is missing" and "is illegible" are grouped away from "reset value". My thinking is that the first two checkboxes reflect a reading of the document in a way "reset value" does not.
* "Reset value" toggles a class on the fieldset that overlays an obstructing white layer over the editable field elements to reflect that they will not be saved on submission. At the moment, the user can still tab through those elements on the keyboard to edit them, but I'm hoping the presentation is enough of a warning. (I'm not sure what to do about users who only use screen readers, though. Any thoughts @mebrett? )

How do we feel about these changes?

**Comment by kimisgold** [comment]
As per our check in discussion, I'll add the disabled attribute to inputs.

**Comment by kimisgold** [comment]
I think everything is in place here: when checking "reset value", the relevant inputs are grayed out and disabled while the "is missing" and "is illegible" common checkboxes remain accessible. Is this ready to close? @jmotis @lmullen

**Comment by jmotis** [comment]
Looks good to me.
