### ISSUE TITLE
New Record --> Focus Mode overlay

### ISSUE THREAD

**Issue by dth1692** [chnm/Datascribe-module#31]
When I add a new record, there is an overlay with the viewing tools.  Sometimes it does not happen- seems to be related to whether I've zoomed in at all prior to entering Focus Mode.  Usually reverts to a normal view when changing the zoom again.  I did this in Edge.
![New Record Focus overlay](https://user-images.githubusercontent.com/35391752/84064299-61d5ae80-a990-11ea-8a04-260d5c7ce1c6.JPG)

**Comment by kimisgold** [comment]
I found this at some point but am having trouble recreating it in my own installation. Could you provide a link on the test installation?

**Comment by dth1692** [comment]
I was able to recreate it on the second try here. I'm not sure why it isn't every time since I'm specifically avoiding changing the zoom before going into Focus mode.  It recreates most of the time in Edge.  I'm not able to recreate it in Chrome.

http://datascribetest.chnm.org/admin/datascribe/2/2/7/record/add

**Comment by kimisgold** [comment]
Just tried in Edge, Chrome, Firefox, zoomed in and out: no dice. This is a bit of long shot, but can you try hard refreshing/clearing your caches?

**Comment by dth1692** [comment]
No luck.  Still getting the overlay but not every time

**Comment by dth1692** [comment]
A different variation of this is occurring now where going into Focus Mode still has the overlay, and now leaving focus mode overlays the Focus Mode and Layout buttons on the New Record page when Previous records is open. It also happens after switching from vertical view but in this scenario, it resets a second later.  When its related to switching in and out of Focus Mode, its dependent on me doing some type of scrolling visual change to the page.  Sometimes it corrects on its own, but not every time and sometimes it does not happen.  It only happened when adding a New Record, not when editing a preexisting record.

Things that correct it: 
- Scrolling the New Record fields
-Zooming in or out
-Resetting the document view
-Rotating the document
-Pan view on the document
-Resizing the window
-Typing in a field
-Collapsing Previous records
-In half screen, clicking to the end of the columns
-Selecting "Insert before" or "Insert after" under position

Things that did not correct it:
-Clicking the document
-Clicking the fields
-Selecting a field
-Checking is missing or is illegible

More success recreating it in Edge, but also able to do it in Chrome.  Of course, as I was doing this, it stopped recreating as easily but still fairly consistent.

![Focus Mode over lay New Record](https://user-images.githubusercontent.com/35391752/85775024-64a10500-b6ed-11ea-93c5-0fc951509bbb.JPG)

Link: http://datascribetest.chnm.org/admin/datascribe/2/2/7/record/add

**Comment by dth1692** [comment]
@kimisgold I'm noticing that this isn't happening in in horizontal view.  The media viewer is more likely to overlay buttons when its to the left of the fields, but it never does that when they are stacked on top of each other.  Something about the layout seems determine if its contained or not

**Comment by kimisgold** [comment]
These errors were possibly a result of using Microsoft Edge Legacy. They work in the current Microsoft Edge.
