### ISSUE TITLE
Deleting Record and Record Numbers

### ISSUE THREAD

**Issue by dth1692** [chnm/Datascribe-module#32]
Deleting a Record removes the number of the record in the listing.  I.e. I created records 39, 40, and 41.  Deleted 41.  Added a new Record that was assigned 42.

I can see his as a helpful to not mess up transcriber notes by changing all the numbers should I go and delete Record 20, ruining any references to later records.  However, my thought process is that if I need to find line 15, I can't assume that Record 15 corresponds to it.

**Comment by dth1692** [comment]
Here's where I think this makes a difference for workflow (I can add this as a separate issue if you think it should be).  When I'm adding records, the Add New Record page doesn't show all the records here and I can't navigate through previous records from here.  If I'm trying to find where in the Record I was, being able to count the lines according to the record number would make this easier/make more sense to me coming in as a transcriber.
![Adding records](https://user-images.githubusercontent.com/35391752/84195275-48a23000-aa6c-11ea-809c-12bc195f7704.JPG)

**Comment by jimsafley** [comment]
A resource's reference identifier should always be unique for the reason you mention above. Even so, that doesn't mean that we can't provide other means to identify a record - the most obvious one being its position in the item. I acknowledge that "Record #" is misleading and should be reserved for the record's position, but we haven't implemented record position, but we plan to (see #36).

**Comment by jimsafley** [comment]
This is partially solved with #36. I think we can close this, even though we're not providing position numbers.
