### ISSUE TITLE
Add+ leaves Focus mode

### ISSUE THREAD

**Issue by dth1692** [chnm/Datascribe-module#34]
When I finish a Record and click Add+ while in Focus mode, it resets so I leave Focus mode to New Record.  Focus mode suggests to me that I could stay in this setting and not see the new record lines until I leave so I don't lose my place or have to restart Focus mode for every record.

**Comment by jimsafley** [comment]
This is something that _may_ be resolved with #37.

**Comment by jimsafley** [comment]
Fixed in 2251687666613019b6625b4aab4ed8d7ac438e0a
