### ISSUE TITLE
Adding Record after skipping a line

### ISSUE THREAD

**Issue by dth1692** [chnm/Datascribe-module#35]
As far as I can tell, if I skip or miss a line in the item, I can only add it as the newest record, wherever correcting the mistake occurs. As far as creating data, this doesn't seem like a problem since the data will still be created, but will this cause challenges on the review end?  Does an 'inset record' option like an insert row in Excel make sense for transcribers to have?

**Comment by jimsafley** [comment]
This is something that will be resolved with #36.

**Comment by jimsafley** [comment]
Fixed with #36
