### ISSUE TITLE
Build a media browser/viewer

### ISSUE THREAD

**Issue by jimsafley** [chnm/Datascribe-module#4]
Users need a way to seamlessly browse through an item's media on the record add, edit, and show pages. On the initial load, this component should render pagination and load the first media in the viewer. The viewer should use existing file renderers to generate markup for each page, except that images should include pan/zoom options. It will need to account for possibly dozens or hundreds of media per item, so it cannot load every media at once. This means it will need a way to fetch individual media pages asynchronously. It should also be modular, meaning it should be rendered on any page that has an item using a view helper. This helper can be provided by the DataScribe module or a separate module altogether (though we need to discuss the pros/cons of adding a dependency).

**Comment by kimisgold** [comment]
We've had a media viewer in place for awhile, along with an asynchronous media selector. For further refinements and bug tracking, let's open new issues.
