### ISSUE TITLE
Condensing Record sections and "This field is required"

### ISSUE THREAD

**Issue by dth1692** [chnm/Datascribe-module#40]
Could the text "This field is required..." be moved to fit next to the data label or can the space on either side of it be condensed?  In focus mode I need to scroll carefully to keep the section label and the 4 options visible at the same time

![Field is required](https://user-images.githubusercontent.com/35391752/84336455-45d73600-ab65-11ea-9d3a-9d3585744ef3.JPG)

**Comment by jimsafley** [comment]
An indication that the field is required must be outside the field's form control (here, the "Number" input) because data types may add more than one input to the control. I recommend we reduce the margins or come up with another, more compact way to indicate a required field.

**Comment by kimisgold** [comment]
This above commit should now be on the shared testing instance.

**Comment by kimisgold** [comment]
Apply required asterisk pattern to required fields.

**Comment by dth1692** [comment]
I like how this looks more.  The one (two?) thought I have is how the red makes it seem like the form won't save or let you finish if you don't include a value there.  The "this value is invalid" warning only goes away after you save the record, so when typing in the values, the red warning message gives the impression that its still incorrectly typed into the field.  

This might also just be the trickiness of having a "required" asterisk next to fields when users need to be flexible about how consistent their documents are with information.  I prefer having the asterisk, but if we can't get the invalid message to disappear after something is typed into the field, we might want to consider ways to make the visual cues look less like a sign that the form won't submit.

![value is invalid](https://user-images.githubusercontent.com/35391752/86161952-0c4a7880-badc-11ea-8977-aeff6710c696.JPG)

**Comment by jimsafley** [comment]
> but if we can't get the invalid message to disappear after something is typed into the field

That's not possible, unfortunately. There's no way for the page to know what constitutes a valid value until it's submitted.

I would have thought the "Please correct it below _and save this form_" message makes it clear that they have to save to the form to validate the value.

**Comment by dth1692** [comment]
That's how I read it first, and then looking at the visual cues from the red writing, I also read it as "correct this and once its correct (ie without an error message), save it".

Its not the most necessary change and if others don't have similar thoughts, we can ignore my color associations.

**Comment by kimisgold** [comment]
Suggestions for clarity re: "invalid" warning:

* "Please correct it below and save this form __to update__."
* Use a container style for the alerts.
* Use orange to further indicate to the user that the form can submit.

**Comment by kimisgold** [comment]
I've applied the changes from my last comment, though I'd like to check on what we want for all the possible alerts. I changed all the alerts requesting some kind of resubmission to the `.warning` (orange) class and left the others as `.error` (red). Is that what we want, or did we want them all orange? 

For clarity, here are all our alerts:

* "This field's data type is unknown. The value cannot be added." (Error/red)
* "This field's data type is unknown. The value cannot be edited." (Error/red)
* "This value is invalid. Please correct it below and save this form to update." (Warning/orange)
* "This value is marked as invalid but does not appear to be invalid. Either re-validate the dataset or save this form as-is." (Warning/orange)

**Comment by jimsafley** [comment]
None of the alerts prevent the form from being submitted, so I think they should all be orange. In addition, I think the required asterisk should be orange for the same reason.

**Comment by kimisgold** [comment]
Everything should be orange now. Do we have anything left before closing this issue?
