### ISSUE TITLE
Auto scrolling numbers

### ISSUE THREAD

**Issue by dth1692** [chnm/Datascribe-module#41]
I've done this a few times now where I type in a number, but because my cursor is still over the Number box and the box is still selected, it auto scrolls for me when I try to scroll down the page.  Since its just a small mouse movement to take the cursor out of the box, I've often moved the mouse enough so that the numbers scroll to 1 or 2 off my typed entry and I've moved down the page without noticing.

This feature is helpful for preset options like years in the Account Books and Bills of Mortality, but for other sections like Number of officers, it causes problems with ensuring the data is accurately counted.  Is this just dependent of the project set up or how the Number input section functions? 

![Numbers](https://user-images.githubusercontent.com/35391752/84421296-59c47b80-abe9-11ea-8967-8605b20e1c9b.JPG)

**Comment by kimisgold** [comment]
Which browser are you using? This isn't a feature we've developed, so I suspect it's a default browser behavior.

**Comment by dth1692** [comment]
I was able to recreate it on Edge and Chrome.  It doesn't happen on the account books except for the dates which have preset options.  For the Household Officers it happens for the number options.  The account books don't have the arrows in the boxes for monetary fields. 
I can see the arrows on the side of the box in both projects when I'm signed in as Global Administrator but not as an Editor.

**Comment by kimisgold** [comment]
I just checked, and these are browser-specific "features". I agree that they're annoying and can be disruptive to the workflow, but I'm also hesitant to mess with a browser default. @jimsafley any thoughts?

**Comment by jimsafley** [comment]
Yes, the "Number" field renders a [number input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number), which for some browsers includes this rather annoying behavior. I could change the input type from "number" to "text" but we would lose the native features of the the "number" type, including minimum value, maximum value, and stepping interval - so that's a non starter. I'll experiment with ways to automatically disable the number scroll using JS.

**Comment by jimsafley** [comment]
[Disabling this behavior](https://stackoverflow.com/questions/9712295/disable-scrolling-on-input-type-number) is not as straightforward as I had hoped. For each solution there is a drawback.

One solution: I could make it so the input loses focus when the user scrolls, which would have the desired effect of scrolling the page and not the input value; but the input would lose focus, which is atypical and possibly undesired behavior.

Another solution: I could disable the scroll when the input is in focus, which would have the desired effect of not scrolling the input value; but the page would not scroll while the input is in focus.

We have to ask ourselves which behavior is least undesirable:

- The current behavior
- Losing input focus on scroll
- Losing page scroll when input is in focus

(If we do disable this behavior, we have to remember to remove the input spinner using CSS.)

**Comment by kimisgold** [comment]
Losing input focus on scroll seems least disruptive to me: I imagine scrolling users are probably not leaning heavily on keyboard navigation, and for those who scroll accidentally, the current behavior is probably worse than losing focus.

**Comment by jimsafley** [comment]
Fixed in 7e6cc5ae8809af55986fb7e4acbc082e613be892
