### ISSUE TITLE
Set to Null invalid

### ISSUE THREAD

**Issue by dth1692** [chnm/Datascribe-module#42]
I'm not sure if this is the parameters of the project setup or not. @jmotis this might be related to setting number of officers to "is missing" per the transcription notes. Setting any of the required fields to null makes the data invalid and does not save that I checked the box.  "Is missing" and "is illegible" are saved and marked null in the record.

I'm guessing setting any of the numeric fields (Number of Officers) to have blank data as missing means that fields (Shillings/Pence) left blank to indicate 0 are following the same valid/invalid input rules.

![Set to null](https://user-images.githubusercontent.com/35391752/84434335-ce091a00-abfd-11ea-971f-e37bcdba0dc4.JPG)

**Comment by jimsafley** [comment]
So it's clear, here's the logic for required fields, regardless of data type:
- Null values are invalid _unless_ they are also marked as illegible or missing
- Illegible or missing values are _always_ valid

**Comment by dth1692** [comment]
Ok- makes sense.  Then the difference here and with the account books is setting the monetary fields to required.  In those, setting to null (which looking back left them blank) did not get marked invalid whereas these are.  So its the projects' differences in required fields and users would likely clarify how to fill these fields in transcription guidelines.
