### ISSUE TITLE
Update jquery.panzoom library to latest without jquery

### ISSUE THREAD

**Issue by kimisgold** [chnm/Datascribe-module#43]
The library we're currently using for panning and zooming media in the records views no longer uses jQuery, which has made troubleshooting issues like #33 cumbersome.

**Comment by jimsafley** [comment]
This will require a complete rewrite of the media viewer, which isn't necessarily a bad thing. It's good that we stay up to date on our dependencies. Here's the [library](https://github.com/timmywil/panzoom) (use `$ npm run-script build` to build the minified script).
