### ISSUE TITLE
Clarifying review status

### ISSUE THREAD

**Issue by mebrett** [chnm/Datascribe-module#44]
Just clarifying that I understand the workflow correctly - when I'm looking at all of the records in an item, as here: 
<img width="1139" alt="Screen Shot 2020-06-15 at 11 47 29 AM" src="https://user-images.githubusercontent.com/2314070/84678517-1f672100-aefe-11ea-95cd-5e4ff940499b.png">

If I take actions in the drawer on the right, it will affect all of the records regardless of whether they're checked or not?

**Comment by jimsafley** [comment]
Yes. The "Item actions" drawer applies to the item and all of its records _as a whole_. The checkboxes are only used for "Batch actions".
