### ISSUE TITLE
Testing: Record position

### ISSUE THREAD

**Issue by jimsafley** [chnm/Datascribe-module#45]
The [record-position](https://github.com/chnm/Datascribe-module/tree/record-position) branch introduces a way for users to adjust the position of records in relation to each other. Now, when adding or editing a record, a reviewer or locked transcriber can select to insert the record before or after another record. The default sorting for the record browse page is now by position rather than by ID.

This is a powerful feature, but also a fragile one, potentially, given the precise adjustments that need to be made to retain consecutive positions. So we need to test this thoroughly, with a close attention to detail. Make position changes to your records using both "Insert before" and "Insert after". Move records from low positions to higher positions and from high positions to lower positions. If you find errors it will be very hard to troubleshoot unless you make notes about what happened before the error.

One important caveat: the upgrade will make changes to your database that can't easily be downgraded. This shouldn't be a problem if you're okay uninstalling the module when switching between the branch version (0.2.0) and the master version (0.1.0). If you already have a bunch of records you're using for testing on master, and you'd prefer not to lose them, I recommend you use a separate Omeka S installation to test this feature.

(This addresses #36)

**Comment by mebrett** [comment]
Given the caveat, it seems that we should *not* test this on the shared testing install. 
I'll look into where we might have a secondary instance to test this.

**Comment by jmotis** [comment]
I can update my Reclaim testing install to use this branch and give other folks accounts on it. Just @mebrett and @dth1692 or does anyone else want an account?

**Comment by kimisgold** [comment]
@jmotis I'd like one as well.

**Comment by jmotis** [comment]
Okay, you all three should have invitations to my test install and I've got the branch installed.

**Comment by lmullen** [comment]
@jmotis Sure, an account would be helpful. Thanks.

**Comment by jimsafley** [comment]
To better verify that the positioning is working as expected, I added a "Position" column to the record browse page (@mebrett you'll need to pull). The position numbers should always be consecutive positive integers (1,2,3,...), and there should be no gaps in position (1,3,4,...) or duplicate numbers (1,2,2,...), even after deleting a record.

A note about the position column: I included it here to assist with testing, but I'm not sure we should include it in the released version. Position should _never_ be used to identify a record because it is mutable. Including it here would possibly lead to bad habits by transcribers, e.g. referencing records by record position instead of record ID. We should discuss this.

**Comment by jmotis** [comment]
My gut instinct would be to NOT include a position column unless people felt strongly they would want/need it in the finished DS.

**Comment by lmullen** [comment]
I think I agree that the position column should not be displayed. Perhaps, though, there is an argument for including it in an export. The argument would be that users can easily discard columns. But they can't easily recreate order, even in a format like CSV that preserves order, and definitely not after importing to a RDBMS where retrieval order is not guaranteed from insert order.

A question to help us decide: It seems clear that order helps with transcription. Does the implicit order of records (in an instance where there is no natural field to be transcribed that provides the order) ever help with data analysis? My initial guess would be no.

**Comment by dth1692** [comment]
So far I have not had any issues with record positions- I've rotated them around the board and between pages, mixed in blank records (none marked invalid b/c the project settings but I don't think that would matter), edited text and position at the same time, changed position to their current position, and put records before and after themselves.

I'll keep trying to think of ways to break it, but if there's anything else you think I should try, let me know.  

The one workflow comment I have is now I've moved records all over the place.  The position changer to before or after gives me placement option by Record # listed in order of position, so finding a number in the hodgepodge is challenging.  Ie Record # 24 in the 15th position is listed as Record # 24 in the 15th row of position options.

If the Record numbers are unique across DataScribe, this might make it harder for transcribers to find where a record goes.  However, it seems like this is also a tool generally intended for transcribers to correct a one-off mistake in the order so it isn't necessarily a problem. Given that the numbers are listed according to the document and Previous/Next records are viewable when editing, you can figure out going back a few rows without much trouble.

I don't think putting the Records #'s in numerical order is a better option, but we might want to consider how accessible/readable it is to scroll through an unordered list of numbers.

![Record number position](https://user-images.githubusercontent.com/35391752/85065608-79c0e580-b17b-11ea-83dd-cf0d3e6c5e6e.JPG)

**Comment by jimsafley** [comment]
I see your concern, but I would not call it an "unordered" list of numbers. They are ordered, but their positions aren't labeled. Nevertheless, even without the labels it should be easier to detect a reference item if the dataset has a primary field. So, instead of this:

```
Record #35
Record #20
Record #25
```
You'll see this:
```
Record #35: War of 1812
Record #20: Spanish–American War
Record #25: World War I
```
So, it'll be easier to place e.g. "American Civil War" in the correct position. At least that's the theory.

**Comment by jimsafley** [comment]
I'm satisfied enough with the results to merge the branch and close this issue.
