### ISSUE TITLE
Testing: Confirm that the add/edit record pages work as usual

### ISSUE THREAD

**Issue by jimsafley** [chnm/Datascribe-module#48]
To prepare for #37 I've consolidated the markup of the add record and edit record pages. Nothing should have changed visually or functionally, but the pages should still be thoroughly tested to confirm this.

**Comment by dth1692** [comment]
I've tried adding, editing records, and editing position.  No changes or problems related to this that I've noticed.

**Comment by jimsafley** [comment]
Thanks!
