### ISSUE TITLE
Previous Record columns missing in half screen

### ISSUE THREAD

**Issue by dth1692** [chnm/Datascribe-module#50]
When I have the browser (Edge and Chrome) in half screen, I am missing columns and the last one is cut off.  There are cutoffs when not on the last page of the columns too.  Here it should end with columns Pounds (L), Shillings (s), Pence (d).  However, its not the first time I use the arrows to go to the last columns.  Its after I go to the end, navigate back to the left columns, and try to return to the end of the line.

Maybe its related to the cell overflow issues referred to in #46 

![Previous Records border](https://user-images.githubusercontent.com/35391752/85772961-5baf3400-b6eb-11ea-95ba-13b8057070fa.JPG)

**Comment by kimisgold** [comment]
Yes, I think it's related, and I just attempted to fix it in 2ed088300c8b13f5503882a100668e266bba6ac8.

**Comment by dth1692** [comment]
It seems like its fixed in Chrome, not in Edge.

**Comment by dth1692** [comment]
Columns are displaying correctly in Chrome and Edge
