### ISSUE TITLE
Testing: Saved state of the media viewer and page layout on "Save progress" and "Add+"

### ISSUE THREAD

**Issue by jimsafley** [chnm/Datascribe-module#51]
The [media-viewer-save-state](https://github.com/chnm/Datascribe-module/tree/media-viewer-save-state) branch is an attempt to resolve #37 by making the "Save progress" and "Add+" workflows more seamless. The idea here is to preserve the the state of the media viewer and page layout after submitting the page. I think is the most jarring part of the current workflow is that the user will have to reestablish the pan, zoom, rotate, focus mode, and layout each time. This should do it for them.

Test this in the record add and edit pages. After submitting the form using "Save progress" or "Add+", any adjustments to the media viewer, focus mode, or layout should be preserved on reload. Note that this will not preserve page scroll.

It's worth noting that the alternative solution (update page state) will be far more difficult to implement and maintain, and potentially more liable result in unexpected behavior.

**Comment by dth1692** [comment]
I'm not seeing any changes on Edge or Chrome.  I'm still leaving Focus mode and the media viewer is resetting when I Add+.  There is also no Save Progress button in Focus mode-

**Comment by jimsafley** [comment]
@mebrett needs to checkout the branch so you can see the changes. @kimisgold and I are brainstorming ways to make "Save progress" visible in focus mode.

**Comment by dth1692** [comment]
I've checked again in Edge and Chrome.  I'm in datascribetest using Transcriber and Global Admin accounts on the Mason account books.  The media viewer resets, as does Focus mode and layout for Add+ and Save Progress.

Am I in the right place or looking at the wrong thing?
