### ISSUE TITLE
No Save Progress button in Focus mode

### ISSUE THREAD

**Issue by dth1692** [chnm/Datascribe-module#52]
For both Edge and Chrome, the Save Progress button disappears when I go into Focus mode.  I think this was originally addressed in #38. With a New record in Focus mode, I can see Cancel, Add+, Add, and Guidelines.

**Comment by kimisgold** [comment]
This should now be addressed in https://github.com/chnm/Datascribe-module/commit/03a9b7408a28cf44c8cfaa52b7dad40780e556d2. The save progress button now sits in the "Save and..." dropdown menu as "Stay on this record", and it should appear within focus mode.

**Comment by jmotis** [comment]
The "Cancel" and "Save and" buttons appear in focus mode in Firefox, but not in Safari. (I didn't double-check Chrome, I assume it's still ok).

**Comment by kimisgold** [comment]
I just pushed a fix on the main branch. @mebrett, can you let @jmotis know when the latest changes have been pulled into the shared install?

**Comment by mebrett** [comment]
@jmotis @kimisgold Just pulled at datascribetest - should now be up to date.

**Comment by jmotis** [comment]
Looks good now, thanks!
