### ISSUE TITLE
Automatically in Focus mode and Delete Button

### ISSUE THREAD

**Issue by dth1692** [chnm/Datascribe-module#54]
What I'm finding is that one I put a New Record into Focus mode and then return to the Records list, going to edit or add a New Record from the table of records automatically goes into Focus mode.  It seems to depend on if the last New Record was added from Focus mode or not. Selecting a record on the table compared to Record to Add Record to Add Record etc... are different tasks.  Not sure about the effect on the workflow yet, but I'll figure out more feedback on that part later.

Where this is causing a problem is that to check the media viewer state, I added a number blank records.  When I went to delete them, it automatically entered Focus mode to edit.  This gave me the Delete button in the right corner, but the confirm delete button doesn't come into frame in Focus mode.  It made it seem like the Delete button was broken.  This could be a good check to avoid accidental deletes, but there is no signal that the Confirm Delete panel opens on the regular Record Page.

![Deleting Focus mode](https://user-images.githubusercontent.com/35391752/86191890-328d0a00-bb16-11ea-9d2a-b3099811bd37.JPG)
![Delete in Focus mode](https://user-images.githubusercontent.com/35391752/86192770-55b8b900-bb18-11ea-887a-101e158e5f6a.JPG)

**Comment by jimsafley** [comment]
Good catches. I've now made it so the media viewer resets when clicking "Cancel", "Delete", and "Save and return to records". It should only save state when clicking "Save and add another" or "Save and stay on this record".

As for the delete drawer expanding under focus mode: we should either hide the delete button in focus mode, or somehow make the drawer appear in focus mode.
