### ISSUE TITLE
Save and... menu in Edge

### ISSUE THREAD

**Issue by dth1692** [chnm/Datascribe-module#55]
The Save and... dropdown menu in Edge is very different from the view in Chrome.  Add another is not visible, Return to Records is offcentered, and it has white space around them. 

![Return to Records button misalignment](https://user-images.githubusercontent.com/35391752/86192911-a4665300-bb18-11ea-908d-80f06db74f29.JPG)

**Comment by kimisgold** [comment]
This is almost certainly a caching issue. Everything looks as it should within Edge for me.

**Comment by kimisgold** [comment]
These errors were possibly a result of using Microsoft Edge Legacy. They work in the current Microsoft Edge.
