### ISSUE TITLE
Re-implement media viewer

### ISSUE THREAD

**Issue by jimsafley** [chnm/Datascribe-module#56]
In an effort to fix issues like #33 and to future-proof the interface, we need to re-implement the media viewer using the most up-to-date [panzoom library](https://github.com/timmywil/panzoom) (see #43).

The new media viewer must retain the features of the current one:

- zoom in
- zoom out
- rotate left
- rotate right
- click-and-drag panning
- scroll wheel zooming
- reset image
- media selection
- media pagination
- focus mode (full screen)
- horizontal layout
- vertical layout
- save state of media viewer using `localStorage`

**Comment by jimsafley** [comment]
This is a work in progress in the [reimplement-media-viewer](https://github.com/chnm/Datascribe-module/tree/reimplement-media-viewer) branch. I changed the media viewer's markup to accommodate the new panzoom structure. It will need restyling. I refactored the media viewer's JS, obviously, but currently the following are not implemented:

- media pagination
- save state of media viewer using `localStorage`

**Comment by jimsafley** [comment]
e58bad4761a2cf0b14eb30298fe616db326cfd08 enables media pagination, so the only remaining feature is save state of media viewer using `localStorage`.

**Comment by jimsafley** [comment]
25330dae12fb5be27c62672ff115c1cf345f8ebb adds a feature not listed above: save state of each image on the current page. So if the user rotates and pans one image, switches to another image, then switches back, the image will retain the previous rotation and position.

**Comment by jimsafley** [comment]
8d49e44af780cbd4aa51f5350a7054cd3bd5a79e applies media viewer state on return to edit page. This should complete the above feature list. However, the media viewer still needs styling.

**Comment by jimsafley** [comment]
@kimisgold This issue required a complete rewrite of the media viewer's markup and JS. Because of this, the styling will need your attention again. The only files that I changed are:

- view/datascribe/admin/record/media-viewer.phtml (rewrite)
- asset/js/admin/media-viewer.js (rewrite, using vanilla JS)

Note that I completely broke the existing styles and made no style changes myself. Feel free to modify media-viewer.phtml to your specifications, but please do not change the ID, value, and disabled attributes, and please do not alter the `#panzoom-container` and its contents in any way. Also, should you need to make changes to media-viewer.js, please consult with me first. The code is a bit finicky due to the saved state implementation. Thanks!

**Comment by jimsafley** [comment]
Hopefully fixed in 08ee1c9616331b3560728080813b256766cb95b8

@mebrett @dth1692 I merged this branch into master, so please pull and review the changes. It should look and behave almost identical. The one biggest difference is the new feature explained in https://github.com/chnm/Datascribe-module/issues/56#issuecomment-663349593 . Please retest the media viewer just to make sure things work as expected.

**Comment by dth1692** [comment]
@jimsafley 2 issues came up.  First, in Chrome the media viewer no longer works in regular and Focus mode.  Its a static image of the media that I can't zoom in on or rotate etc

Second, in Edge it preserves the media viewer.  However when I work in Focus mode and click Save and Add another, it leaves Focus mode to the New Record page like this:
![Media viewer disappears](https://user-images.githubusercontent.com/35391752/89701356-227dfc80-d904-11ea-8256-5e1ae396f514.JPG)

The viewer does return and preserve the state going back into Focus mode from here, but the media viewer wouldn't restore on the the New Record page.

**Comment by jimsafley** [comment]
> First, in Chrome the media viewer no longer works in regular and Focus mode. Its a static image of the media that I can't zoom in on or rotate etc

This may be a caching issue. Try hard refreshing your browser several times. If that doesn't work then it's probably a JS error. Open your browser's debugger and see if there's an error in the console.

> However when I work in Focus mode and click Save and Add another, it leaves Focus mode to the New Record page 

Good catch. I forgot to save fullscreen and layout state. I was too preoccupied with saving pan/zoom state to remember. I'll get to it next week.

**Comment by jimsafley** [comment]
@dth1692 Ok, the media viewer now saves fullscreen and layout state. Try it out after @mebrett pulls. Remember to hard refresh your browser to avoid caching issues.

**Comment by dth1692** [comment]
@jimsafley its working in Chrome- the media viewer saves its state when I change Focus mode, leave the record, and save.  However- now it the buttons for the media viewer, layout and Focus mode don't work in Edge. But I can move the image around so the media viewer is somewhat working.  It does not let me Zoom manually.

The strange thing in Chrome is that when I refresh the page, it saves the media viewer state but opens in Focus mode.

**Comment by jimsafley** [comment]
@dth1692 I made some changes that should fix the refresh bug you noticed. Now, the media viewer saves state after every user interaction, not just during form submit. Try it out once it's pulled. Again, a hard refresh will be necessary, as always when testing new JavaScript.

**Comment by dth1692** [comment]
Its working and saving state each time.  No Focus mode opening or any issues with that.  However the media moves around a lot when I change the window size.  I'll open a new issue for that
