### ISSUE TITLE
Save in Form builder

### ISSUE THREAD

**Issue by dth1692** [chnm/Datascribe-module#57]
Save and Save Progress do different things.  My inclination is to click Save in the upper right rather than Save Progress which exits the Form builder.  Its seems very similar to adding a Record that I'm following a similar workflow but the buttons don't translate.  

I think a quick fix would be to turn the Save button to Finish or Finish and Save to distinguish it from Save Progress.  I also have a base assumption that the red Delete button means those buttons are the primary ones to use, so maybe making it gray or giving Save Progress a color other than gray will visually indicate which ones to primarily use.

**Comment by kimisgold** [comment]
I just condensed the save actions into that dropdown menu, but I'd like folks to review the copy for the action labels: 

"Save and..."

* "Return to dataset items"
* "Continue editing dataset"
