### ISSUE TITLE
Testing: Verify that  data types work

### ISSUE THREAD

**Issue by jimsafley** [chnm/Datascribe-module#6]
The `plain-text` branch makes some far-reaching changes of the way DataScribe stores values. Please test each data type (including the new Date and Time data types). There should be no change from previous behavior.

**Comment by mebrett** [comment]
The step function for numeric doesn't seem to work? I can't get it to accept a value, even one it suggests.
No other bugs yet.

**Comment by jimsafley** [comment]
Numeric step is an odd one and will need further attention, eventually.

I've added a new Checkbox data type that needs testing.

I've also changed how values are stored when no input is given. Before it set them as empty strings, now it sets them to NULL, which is always valid. A minor change with major implications, but I feel it should be default behavior.

**Comment by mebrett** [comment]
What's the expected behavior for checkbox?

**Comment by jimsafley** [comment]
The Checkbox data type adds a boolean control, a checkbox that results in a checked value or an unchecked value.

**Comment by mebrett** [comment]
Example use case?

**Comment by jimsafley** [comment]
It answers yes/no or true/false questions about a record.

**Comment by mebrett** [comment]
It's going to take some documenting to explain how to implement this in a way which won't trip up the users, because the Checkbox option looks so much like the check boxes for null and illegible when you're working through. But it works.

**Comment by jimsafley** [comment]
I think @kimisgold has some style changes in a PR that differentiates the is_missing and is_illegible checkboxes from the other data type controls.
