### ISSUE TITLE
Dots overlay

### ISSUE THREAD

**Issue by dth1692** [chnm/Datascribe-module#60]
The dots to navigate the columns overlay some of the field headings 

![dots overlay](https://user-images.githubusercontent.com/35391752/87753250-33899100-c7d0-11ea-9e76-ee0233544293.JPG)

**Comment by kimisgold** [comment]
I just pushed an attempt to fix this that comfortably allows 2 rows of minimap dots, less comfortably 3. @mebrett, can you tag @dth1692 here whenever this change is pulled into the shared install and ready to test?

**Comment by mebrett** [comment]
@dth1692 @kimisgold Just updated datascribetest.

**Comment by dth1692** [comment]
Looks like they work- for one and two rows.  Then if it matters- for a third row, they go slightly over the line. I had to adjust my window to less than 1/4 width to get another row so it might have altered it.
![minimap dots](https://user-images.githubusercontent.com/35391752/87959633-2e06a200-ca81-11ea-90b8-927811bbf2ee.JPG)

**Comment by kimisgold** [comment]
I think the columns we support for the moment should be good enough. We can revisit making three rows look nicer when there's more demand.
