### ISSUE TITLE
Very large area for advanced search button

### ISSUE THREAD

**Issue by mebrett** [chnm/Datascribe-module#61]
On the items page, I was clicking back into the browser window and ended up on the advanced search page. 
A quick look in the inspector shows that the clickable area for the advanced search button extends pretty far to the right of the text:
<img width="484" alt="datascribe_searcharea" src="https://user-images.githubusercontent.com/2314070/88936070-71ff6100-d250-11ea-8e63-66c164167e23.png">

I like the idea of the clickable area being larger than the text alone, but half of the present width seems reasonable?

**Comment by kimisgold** [comment]
That was a by product of some unnecessary positioning that I just undid. It should be the width of its contents now.

**Comment by kimisgold** [comment]
@mebrett This should be pulled in with the changes from #52. Can you give this a quick look?

**Comment by mebrett** [comment]
Yes, fixed. I'm not longer in danger of hitting advanced search accidentally. thanks!
