### ISSUE TITLE
Image repositioning with keyboard

### ISSUE THREAD

**Issue by jmotis** [chnm/Datascribe-module#62]
Right now, when I'm looking at an image in focus mode and zoomed in so that I can't see the whole image, the only way to reposition the image and see other parts of it is with the mouse (my wrist hurts already and I've only transcribed one field! :P )

How difficult would it be to make it possible to use keyboard navigation to reposition the image when it's selected? I'm marking this as a feature request/Beta feature in case it's a difficult ask.

**Comment by lmullen** [comment]
From meeting: @mebrett, could you please look into best practices for this?

**Comment by mebrett** [comment]
The most common implementation I've found is adding a + shaped button with reset in the center. [For example](https://codepen.io/peterquale/full/rReOmL).

**Comment by kimisgold** [comment]
Jessica also mentioned [Google Maps](https://maps.google.com) as an example. In this example the user can tab focus to the map container, upon which directional keybinds are enabled for panning the map.

**Comment by jimsafley** [comment]
We've decide the best course of action is this: make the panzoom container focusable, and, when it's focused, enable the arrow keys for image panning.

**Comment by jimsafley** [comment]
Fixed in a0c32a2271c0222bf3885c71998b6e1438cc5b90
