### ISSUE TITLE
Hitting enter in record edit saves and starts new record

### ISSUE THREAD

**Issue by jmotis** [chnm/Datascribe-module#64]
I hit enter by accident when I was transcribing (in Firefox) and it saved my current record and started a new one. Saving is fine but I was startled by the behavior of starting a new record because for a moment it looked like it had actually reset the whole record and deleted everything I'd entered despite the save message.

Could we change this so enter saves and returns to the same record? Alternatively, if that's not doable, edit the save message to make clear what's happening?

**Comment by jmotis** [comment]
I can't replicate this behavior in Safari

**Comment by lmullen** [comment]
When one saves the record, the message should include contextual information (e.g., you've successfully saved, and added another record).
