### ISSUE TITLE
No "Add another" option when editing records

### ISSUE THREAD

**Issue by dth1692** [chnm/Datascribe-module#65]
I can't remember if we discussed this before, but I noticed that when editing records, the Save and Add another option isn't available.  I don't think this causes any issues that the record position feature addresses but figured I'd bring it up.  It might just be a distinction between adding a New Record and editing records worth mentioning in the documentation.

**Comment by jmotis** [comment]
@mebrett add to documentation - this is currently intentional

**Comment by kimisgold** [comment]
Discussion notes that might help guide the documentation copy:

We conceptualized "Save and add another" for users creating many records in one session. We imagine that in the "edit record" context, the user (either a reviewer or the original transcriber) is much more focused on the single record they're viewing. "Add another" doesn't make as much sense there, and can stay left out of the edit views in the interest of conserving space in the page actions area.
