### ISSUE TITLE
Improving speed of transcription

### ISSUE THREAD

**Issue by lmullen** [chnm/Datascribe-module#67]
One thing to consider over the long run is what can be done to improve the speed with which a user can transcribe. This would encompass things like keyboard shortcuts and the like.

One suggestion, if it can be done without degrading accessibility, would be to let the user tab through the main inputs for each field, and skip over the missing/illegible check boxes. That way in a normal case, a user can focus just on entering the information and tab through quickly, breaking to use the mouse only if there is a difficult to transcribe field.

**Comment by jimsafley** [comment]
The [fast-tab](https://github.com/chnm/Datascribe-module/tree/fast-tab) branch adds a "Fast tab" button to the record form that toggles (hides/displays) all common elements (missing/illegible/reset). When hidden, tab skips over them but they are still submitted. Try it out.

**Comment by kimisgold** [comment]
I think it looks great so far. I'll make a couple style adjustments for polish. Can we discuss a nicer label for that button? Some ideas:

* Toggle common value flags
* Show/hide common value fields
* Fast entry mode
* Only show data type fields/Show all fields

**Comment by jimsafley** [comment]
Of those options I prefer "Fast entry mode" because it's concise and similar to "Focus mode."

**Comment by jimsafley** [comment]
I merged the fast-tab branch into master in df49106cc529c15d632a3f4bb440c51991714fdf. Should the "Fast entry mode" button be next to the layout controls (as it is now) or next to the "Guidelines" button?

**Comment by kimisgold** [comment]
It's an action that affects the form, so I think it should stay on the left. I might bump it left of the layout controls to keep the "modes" together.

Speaking of which, those button labels should probably provide better reflect the current form state. "Focus/Context Mode" and "Fast entry/Full form Mode" maybe? Or "Focus mode on/off" and "Fast entry mode on/off".
