### ISSUE TITLE
Display issues for record browser on items in Safari

### ISSUE THREAD

**Issue by lmullen** [chnm/Datascribe-module#68]
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/183672/90040405-dfba7c80-dc95-11ea-8dab-ddea888f30f1.png">

The screenshot above shows an example of a display bug in Safari.

**Comment by kimisgold** [comment]
Could you empty your cache and confirm that you're still seeing the layout bug with the column minimap? This is what I'm seeing in Safari on my machine:

![Screen Shot 2020-08-14 at 11 43 10 AM](https://user-images.githubusercontent.com/606764/90267522-ab74c680-de23-11ea-8396-f9266634cdfc.png)

(The filter and sorting elements look the same for me, and I [just pushed some style changes](https://github.com/chnm/Datascribe-module/commit/24bffe7ce439c67b6f9f57f3ef872f6d7e5ae09a) for those.)

**Comment by lmullen** [comment]
I did my darndest to clear the caches and to hard refresh. I also looked in the Safari dev tools and it does appear to be pulling a fresh copy of the CSS, and when I looked at the CSS, it appears to have the change sin the commit you linked above. But the dots still look like the screenshot I posted.

**Comment by jmotis** [comment]
I'm also seeing it visualize correctly when I check the CHNM dev site using Safari. @lmullen I just updated my dev install to the latest version in case you want to try replicating the error there?

**Comment by mebrett** [comment]
Unable to duplicate on Safari Version 13.1.2 (14609.3.5.1.5) on a Mac running 10.14.6

**Comment by jmotis** [comment]
Reiterating my above with more details: couldn't duplicate it on Safari Version 13.1.0 on a Mac running 10.14.6

I've sort of managed to duplicate it on a Safari Version 13.0.5 on a Mac running 10.15.3 by shrinking the window width as much as I could - the issue went away as soon as I widened it back out again: 
![image](https://user-images.githubusercontent.com/8195932/91333218-50d05880-e79b-11ea-8803-c3775e1a927e.png)

**Comment by lmullen** [comment]
An OS upgrade was waiting for me, and that brought me up to Safari 13.1.2. Cleared caches, hard refreshed, etc etc. Then specifically cleared the cache for chnm.org, and I know it worked because it immediately logged me out. Logged back in and have a screenshot that looks the same as above. Confirmed in devtools that it's loading a fresh version of all CSS.

Not sure what else to try, except that this probably isn't worth spending any more time on unless someone else can reproduce it.

**Comment by kimisgold** [comment]
I'll close this until someone can reproduce it.
