### ISSUE TITLE
Media moves a lot when changing window size

### ISSUE THREAD

**Issue by dth1692** [chnm/Datascribe-module#69]
When I change the window size, the media viewer moves the item image around and in many cases, the item is lost somewhere outside the visual so I'm seeing a white void.  I thought the media viewer just wasn't showing the image until I zoomed out enough to find the media again.

I zoomed in as far as possible on the upper left corner of the item in full screen.  Then I moved to half screen and it took 6 zoom out clicks to get any part of the image back into the media viewer again.

**Comment by jimsafley** [comment]
I see what you're describing, but I have no solution. Panzoom (the JS library powering the media viewer) automatically adjusts the image size when the viewport changes, which can push the image off the canvas, especially when zoomed in a great deal and panned to one side. Maybe there's a way to always keep a portion of the image visible in the canvas, but Panzoom does not provide that configuration.

I question how often this will happen and whether it's worth our time to explore further. @kimisgold Do you have any ideas?

**Comment by kimisgold** [comment]
@jimsafley I think panzoom has a [bounds](https://github.com/anvaka/panzoom#user-content-bounds-on-panzoom) configuration we can set. You can see it working with [this demo](https://anvaka.github.io/panzoom/demo/index.html). Can we experiment with that?

**Comment by jimsafley** [comment]
Unfortunately that's not the library we're using. We're using [this Panzoom](https://github.com/timmywil/panzoom).

**Comment by kimisgold** [comment]
I see this happening problem most often when toggling Focus Mode. When switching modes, could we check the image position and reset it if it's fully out of bounds?

The reset button is the best I can recommend in the meantime.

**Comment by jimsafley** [comment]
Calculating whether the image is within its container's viewport may be beyond my mathematical abilities. We'd have to get the following:

- the image's current x,y coordinates from the panzoom object
- the image's rotation from its transform matrix (converting it to degrees?)
- the dimensions of the image at its current state
- the dimensions of the viewport at its current state

Then we'd have to use these figures to calculate whether the image is within the viewport. This is where I lose my ability.

I also recommend just using the reset button.

**Comment by kimisgold** [comment]
Totally fair. Let's backburner this for the moment, and maybe document the reset button recommendation. @mebrett
