### ISSUE TITLE
Testing: Required fields

### ISSUE THREAD

**Issue by jimsafley** [chnm/Datascribe-module#7]
The [required-fields](https://github.com/chnm/Datascribe-module/tree/required-fields) branch introduces required fields. Form builders can now mark fields as required, which makes `null` values invalid. (Previously, all `null` values were valid.)

To test this feature, open the form builder, add a field, and check the "Field is required" checkbox. Then go to add a record and submit an empty value for the required field. The value should be marked as invalid on the browse page and when you go to edit the record. Once you enter a non-`null` value, the value should not be marked as invalid anymore.

Note that you'll need to uninstall and reinstall the module after pulling the branch since the data model changed.

**Comment by mebrett** [comment]
I am able to save when the required value is empty, but does mark it as invalid.
It also marks as invalid if I check that the value is Missing.

**Comment by jimsafley** [comment]
Thanks!

> I am able to save when the required value is empty, but does mark it as invalid.

This is expected. Given the messy and iterative nature of data entry, we don't want to prevent a record from being saved just because a value is empty, even if its field is marked as required. This way, transcribers can do a partial-transcription and then return to finish it.

> It also marks as invalid if I check that the value is Missing.

Hmm. I'm tempted to leave this as-is since "missing" is just a simple flag that can mean different things to different projects. I mean, I understand that if a value is missing, it stands to reason that it's not necessarily invalid, but if the value is missing _and_ required, it also stands to reason that it is invalid. It just depends. Up until now I haven't tied "missing" or "illegible" to any behavior logic, and I'd rather not go down that road without intensive user testing.

**Comment by mebrett** [comment]
My question is whether there will be a way for a reviewer to clear that flag without removing the requirement. I can see use cases where the form creator sets a number of things required, not all of which are always present in the actual data.

I think we can stick with what we have until user testing. We may eventually need a way to override the invalid flag in order to export/save the data.

**Comment by jimsafley** [comment]
Export will treat invalid values the same as missing/illegible values without text: both will result in empty cells. So I'm not sure why there would be a need to override the invalid flag for export.

**Comment by mebrett** [comment]
In that case I don't foresee it being an issue (although user testing may prove otherwise)

**Comment by jimsafley** [comment]
After further consideration, I think it's a great idea to tie the "missing" and "illegible" flags to whether a required value is valid. I've made the change.
