### ISSUE TITLE
Batch Reviewer note

### ISSUE THREAD

**Issue by dth1692** [chnm/Datascribe-module#71]
I edited the Form for Religious Ecologies and went to unapprove the previously approved items.  I can do that, but I can't leave a note saying why there is a change in Review Status on all of them at once.  This would probably be helpful for large scale edits to an ongoing project so transcribers can be given specific instructions about mass review changes without counting on them to infer from the Last reviewed date

**Comment by jimsafley** [comment]
I could add transcriber and reviewer notes at the dataset level, but we should wait until after we've tested and perfected the existing notes at the item and record levels.

**Comment by jimsafley** [comment]
We're holding off on implementing this feature until we have a better understanding of user needs. Until then we'll recommend in documentation that dataset-level notes are better suited using other forms of communication, like email. Closing this issue for now.
