### ISSUE TITLE
Visual glitch when using focus mode and page action menu

### ISSUE THREAD

**Issue by jimsafley** [chnm/Datascribe-module#72]
In Chrome (84.0.4147.135), on the record edit page (note: _not_ the record add page), there's a strange visual glitch after going into and out of focus mode and then clicking on the page action menu ("Save and..."):

![after](https://user-images.githubusercontent.com/141955/91475411-8b082b80-e869-11ea-940a-176ec6d3479c.png)

**Comment by kimisgold** [comment]
I'm having trouble reproducing it in the same Chrome version on macOS and Win10, on both the testing install and locally. It looks like the page is being reloaded in the sidebar area...is it possible there's some ajax oddity being loaded into to a sidebar? Can you interact with any of those elements?

**Comment by jimsafley** [comment]
I can interact with the elements as usual. Worth mentioning: when the focus changes to one of the textareas, the glitch disappears.

**Comment by kimisgold** [comment]
Okay, I was just able to reproduce it after clearing cache. Searching for similar issues, its cleared up when I turned off hardware acceleration within Chrome's settings. Could you try that and see if that clears the glitch for you?

**Comment by jimsafley** [comment]
I turned off hardware acceleration, relaunched, cleared cache and it still shows the glitch. Worth mentioning: the glitch does not appear when DevTools is open.

**Comment by jimsafley** [comment]
We've pinpointed this as a bug specific to Chrome version and/or hardware acceleration. It's not present in the most recent versions of Chrome or other browsers. There is nothing we can do, so closing this issue.
