### ISSUE TITLE
Testing: Using arrow keys to pan image

### ISSUE THREAD

**Issue by jimsafley** [chnm/Datascribe-module#73]
On the master branch, you can now pan the image using the arrow keys when the panzoom container is in focus (#62). You can focus the container by tabbing to it or clicking on it. Once the container is out of focus, the arrow keys should revert back to their default behavior, whatever that is for the browser. When using the arrow keys, does the image pan too slowly? I could speed it up.

**Comment by mebrett** [comment]
Works fine for me. The pan speed is good for me - much faster and I might overshoot my goal. 
I'd like to get a few more eyes on this, but I think it's good.

Funny sidenote - I'm so used to finger scrolling that I initially used the keys in the wrong direction (pressing the up arrow to go down). I think that's user error and it does *not* make sense to switch things around. Just a sign of the dominance of smartphone interfaces.

**Comment by jmotis** [comment]
Also some of us set up our smartphone interfaces so that they match keyboard scrolling instead of being backwards ;-)
