### ISSUE TITLE
Record flagged for review not showing up in dashboard view

### ISSUE THREAD

**Issue by jmotis** [chnm/Datascribe-module#74]
A record flagged for review is not showing up when I use the dashboard link to show all things needing review for that project/dataset. I assume this is because we've set up to show *items* that need review but not individual *records* that are flagged for review.

In case it matters, it's Record #192 (locked to Megan) in the Queen Elizabeth's Household Officers (which I own) and this is in Safari 14.0 (the newest update) as well as Firefox.

**Comment by jimsafley** [comment]
This is expected. The "Items needing review" filter simply shows items that have been formally submitted for review. Flagging a record as "needs review" simply foregrounds that record as needing attention during any stage of the transcription process. Perhaps we can use something other than "needs review" to avoid this confusion?

**Comment by mebrett** [comment]
Add "records needing review" to dashboard (for owner/reviewers)
