### ISSUE TITLE
Formatting of record browse table in certain situations

### ISSUE THREAD

**Issue by lmullen** [chnm/Datascribe-module#76]
<img width="943" alt="image" src="https://user-images.githubusercontent.com/183672/108562642-2be21b80-72ce-11eb-900d-9bf1d77d652b.png">

I'm not sure if the issue here is the long field names or the large number of fields or both, but the formatting of this table in certain situations ends up overlapping.

**Comment by jmotis** [comment]
@lmullen is this still an issue on your install? @mebrett thinks it may be an off-and-on issue as various browsers are updated. Maybe we need to hard code in a max number it displays at once?
