### ISSUE TITLE
Vertical mode for focus mode has image break out of container

### ISSUE THREAD

**Issue by lmullen** [chnm/Datascribe-module#78]
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/183672/109056175-1c881700-76ae-11eb-8511-4f0556210ea6.png">

If I am adding a record, choose "Focus mode" and then choose the vertical version (up and down arrow), the image breaks out of its container and overlaps with the form below.

The screenshot above is from Safari, in case Safari is being a special snowflake.

**Comment by lmullen** [comment]
It's then impossible to get out of focus mode, because the image blocks clicks to the focus mode button.

**Comment by jimsafley** [comment]
@kimisgold Is this because of 90e87185b2e0c0eea18b73044aa7783d157e7b59?

**Comment by kimisgold** [comment]
Quite possibly; I'll look into it.

**Comment by kimisgold** [comment]
I've pushed a fix in https://github.com/chnm/Datascribe-module/commit/d6da7f1ad71077d6bd778b961d1c30017f032c84. @lmullen, could you test to see if this resolves the issue for you?

**Comment by lmullen** [comment]
@kimisgold I just tested it. Works great for me. Thanks!
