### ISSUE TITLE
Cannot use arrow keys

### ISSUE THREAD

**Issue by hammondjk14** [chnm/Datascribe-module#80]
I’m unable to edit the text box entries easily. If I see a typo or need to add to the existing entry, I have a hard time editing the existing text box, because the arrow keys will not function. I can highlight the text, dragging to the end of the entry to click at the end to add more text. Still, using arrow keys is not an option.

**Comment by jmotis** [comment]
I just confirmed this on Safari 14.0.03. When I go in after I've submitted a record and click into a text field, I can't use the arrow keys to navigate back and forth along the string of text, I have to use the mouse.
