### ISSUE TITLE
Feature Request: Subsetting Items by Property

### ISSUE THREAD

**Issue by gswain2** [chnm/Datascribe-module#81]
In Omeka S, a user can use the Advance search on the Items view to search/filter for specific items or types of items. Users can “Search full-text” or “Search by value” (select a property, and then dictate what value you want the property to have). This is extremely helpful in finding subsets of items. (For Religious Ecologies, I use this feature all the time to subset items from a single denomination—ex. “Denomination ID” = “0-0-1”.) Could this same feature be available in DataScribe?

I acknowledge that DataScribe already lets you filter items by status (new, in progress, approved, not approved, invalid, need review, etc.), who they belong to (all items vs. my items), and by lock status (ex. unlocked new items). However, I have yet to figure out how to subset DataScribe items by a property. (Or even to do a full-text search.) The best I can do right now is sort items by title ascending, and then click through hundreds of pages of items until I find what I am looking for. (And this only works for Religious Ecologies because the items titles include the denomination names.)

I think the problem may be that even though there is rich metadata associated with the items in Omeka, only a minimal amount of metadata is imported/transferred to DataScribe, making it impossible to sort/filter by a property that is not there. However, subsetting by a property would be extremely helpful in managing transcriptions on a project with a large number of items.

**Comment by jmotis** [comment]
This gets into questions of workflow. How much do we want people to search within DataScribe vs. do that work ahead of time when creating the project/dataset to transcribe?

**Comment by mebrett** [comment]
@gswain2 The pull request which Jim submitted changes the advanced item search to look like this:
![Screen Shot 2022-01-13 at 10 21 27 AM](https://user-images.githubusercontent.com/2314070/149357989-97d69ee1-c599-437f-8822-08f387fcb23d.png)

I have the pull request active on the shared datascribe testing install, if people want to take a look and try it out.
