### ISSUE TITLE
Moving the image in Focus mode removes header buttons

### ISSUE THREAD

**Issue by dth1692** [chnm/Datascribe-module#87]
In Edge, Safari, and Chrome, when I enable focus mode and Zoom into the image, clicking to move the image will cause the box to resize and cover the disable Focus mode button, switch photo option, etc.  The record name, cancel, and "Save and" bar overlays the top of the page.
![focus mode](https://user-images.githubusercontent.com/35391752/130850115-683792fb-3f84-4980-a165-ec3c41953327.PNG)

**Comment by kimisgold** [comment]
I'm having trouble reproducing this in Chrome, Safari, and Firefox. @mebrett, could you test and see if it's still an issue?

**Comment by mebrett** [comment]
It hasn't done that to me in a while. @dth1692 are you still experiencing this?
