### ISSUE TITLE
Add tooltips

### ISSUE THREAD

**Issue by mebrett** [chnm/Datascribe-module#89]

**Comment by kimisgold** [comment]
Here are my suggestions for the aria-label/title attributes. 

> On record list view, it would be helpful to have a tooltip to for the record number - there are tooltips for the edit and details icon, but nothing that explains what clicking on the number does.

I can see how this is confusing. Typically the sort of row header is a title that's more self-evident as a link to a show view. For words/phrases that we already provide for translation, we could use "View" or "Values". If you think there's enough demand for specificity to justify a new string, maybe "View record values"?

> for the dot-horizontal scroll on the record view, having the left/right arrows say "scroll left" for people who don't immediately understand that the .... < > is a scroll option.

All our pagination defaults to "Previous" and "Next". Would that be enough?

> in transcription view, tooltip for next/previous page would be helpful, to clarify that it's navigating the media and not the form.

"Previous media"
"Next media"

**Comment by kimisgold** [comment]
@mebrett @jmotis When you have a moment, could you give your thoughts on these suggestions? I can implement the tooltips as soon as I get confirmation on the content.

**Comment by mebrett** [comment]
For the record number, I think "View" is sufficient. It's consistent with elsewhere in the system. 

Do we think it would be too busy to make the dot-scroll icons say "previous field" and "next field"? If we then made the next/previous in the transcription view "previous media" and "next media" that would be consistent terminology. 

Jessica - thoughts?

**Comment by jmotis** [comment]
View is fine by me. I like the idea of previous field/next field in parallel with previous media/next media if it's not too busy.
