### ISSUE TITLE
Testing: Export dataset

### ISSUE THREAD

**Issue by jimsafley** [chnm/Datascribe-module#9]
The [export](https://github.com/chnm/Datascribe-module/tree/export) branch introduces the export dataset feature. You'll need to uninstall and reinstall the module for this to work. To export a dataset, go to the dataset show / item browse page and click on the "Export dataset" action in the top right. Once this is done, you should see a link to the CSV file at the bottom of the dataset sidebar. Note that

**Comment by mebrett** [comment]
Exports only approved data - is this correct?

**Comment by jimsafley** [comment]
Yes, the exported file will only include records from approved items.

**Comment by mebrett** [comment]
It works  - the data is there, formatted in ways which make sense. There's no clear correlation or way to get from this data to the individual items in Omeka but I don't think that's part of the expectation

**Comment by jimsafley** [comment]
Thanks for testing this. The exported data should include the corresponding record ID as the first column. Once I build the record show page, users can cross-reference that ID with the record, then the DataScribe item, then the Omeka item.
