### ISSUE TITLE
hide projects user can't touch from user in dashboard

### ISSUE THREAD

**Issue by jmotis** [chnm/Datascribe-module#90]

**Comment by jimsafley** [comment]
Is this still necessary if we prioritize the "My projects" section on the dashboard? At any rate, if project owners don't want their projects to be visible, they could just mark them as private. I think there is value in not hiding public projects from users, especially  when the "My projects" section is prioritized.

**Comment by jmotis** [comment]
That sounds like a good potential solution, yes
