### ISSUE TITLE
rename "my items" as "locked to me" in dashboard

### ISSUE THREAD

**Issue by jmotis** [chnm/Datascribe-module#92]

**Comment by jimsafley** [comment]
The module uses "My items" or some variation as filters on the browse items page:

- My new items
- My in progress items
- My items that need review
- My items that are not approved
- My items that are approved

Should these be changed as well? Something like:

- New items locked to me
- In progress items locked to me
- Items locked to me that need review
- Items locked to me that are not approved
- Items locked to me that are approved

I do have to say that I prefer the original, more concise phrasing.

**Comment by mebrett** [comment]
This issue came out of user testing - the desire was to clarify in some way what exactly "my items" were for people looking at the dashboard. 

I could go either way on the filter. Using "Items locked to me" might end up making more sense for a split (ref #93)

**Comment by jimsafley** [comment]
How about this:

- Locked to me: new items
- Locked to me: in progress items
- Locked to me: items that need review
- Locked to me: items that are not approved
- Locked to me: items that are approved

**Comment by jimsafley** [comment]
I think a good compromise here (and this relates to #93) is to keep the filter names as-is, and change "My items" to "My items (locked to me)". Using "My" as a shorthand for "Locked to me" is convenient shorthand. I agree with the need to be more specific in the dashboard, but I also think keeping "My" would help with continuity across the interface.
